### ISSUE TITLE
Broken tests on master after webhook merge

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-server#58]
@laghee so here some meat to work on. :)
All the errors have the same type.

```
.............EEE..EEEE......E
======================================================================
ERROR: test_extract_issue_event_info (tests.unit.test_webhooks.TestWebhooks)
Extract the right information from an issue event.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 169, in test_extract_issue_event_info
    json_event, signature = event_data('issue_body_edited.json')
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 36, in event_data
    sig=helpers.get_payload_signature(key, json_event.encode('utf-8')))
  File "/Users/karl/code/ochazuke/ochazuke/webhook/helpers.py", line 28, in get_payload_signature
    key = key.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

======================================================================
ERROR: test_fail_on_bogus_signature (tests.unit.test_webhooks.TestWebhooks)
POST with bogus signature on ghevents webhook is forbidden.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 93, in test_fail_on_bogus_signature
    json_event, signature = event_data('issue_body_edited.json')
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 36, in event_data
    sig=helpers.get_payload_signature(key, json_event.encode('utf-8')))
  File "/Users/karl/code/ochazuke/ochazuke/webhook/helpers.py", line 28, in get_payload_signature
    key = key.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

======================================================================
ERROR: test_fail_on_invalid_event_type (tests.unit.test_webhooks.TestWebhooks)
POST with event other than 'issues', 'milestone', 'label', or
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 106, in test_fail_on_invalid_event_type
    json_event, signature = event_data('issue_body_edited.json')
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 36, in event_data
    sig=helpers.get_payload_signature(key, json_event.encode('utf-8')))
  File "/Users/karl/code/ochazuke/ochazuke/webhook/helpers.py", line 28, in get_payload_signature
    key = key.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

======================================================================
ERROR: test_ignore_undesirable_issue_action (tests.unit.test_webhooks.TestWebhooks)
Uninteresting issue actions are accepted but not processed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 143, in test_ignore_undesirable_issue_action
    json_event, signature = event_data('issue_body_edited.json')
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 36, in event_data
    sig=helpers.get_payload_signature(key, json_event.encode('utf-8')))
  File "/Users/karl/code/ochazuke/ochazuke/webhook/helpers.py", line 28, in get_payload_signature
    key = key.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

======================================================================
ERROR: test_ignore_unimportant_milestone_action (tests.unit.test_webhooks.TestWebhooks)
Uninteresting milestone actions are accepted but not processed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 156, in test_ignore_unimportant_milestone_action
    json_event, signature = event_data('milestone_closed.json')
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 36, in event_data
    sig=helpers.get_payload_signature(key, json_event.encode('utf-8')))
  File "/Users/karl/code/ochazuke/ochazuke/webhook/helpers.py", line 28, in get_payload_signature
    key = key.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

======================================================================
ERROR: test_ignore_unknown_action (tests.unit.test_webhooks.TestWebhooks)
POST with an unknown action fails.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 130, in test_ignore_unknown_action
    json_event, signature = event_data('issue_event_invalid_action.json')
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 36, in event_data
    sig=helpers.get_payload_signature(key, json_event.encode('utf-8')))
  File "/Users/karl/code/ochazuke/ochazuke/webhook/helpers.py", line 28, in get_payload_signature
    key = key.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

======================================================================
ERROR: test_is_github_hook (tests.unit.test_webhooks.TestWebhooks)
Validation tests for GitHub Webhooks.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 451, in test_is_github_hook
    json_event, signature = event_data('issue_body_edited.json')
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 36, in event_data
    sig=helpers.get_payload_signature(key, json_event.encode('utf-8')))
  File "/Users/karl/code/ochazuke/ochazuke/webhook/helpers.py", line 28, in get_payload_signature
    key = key.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

======================================================================
ERROR: test_success_on_ping_event (tests.unit.test_webhooks.TestWebhooks)
POST with PING events just return a 200 and contains pong.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 119, in test_success_on_ping_event
    json_event, signature = event_data('issue_body_edited.json')
  File "/Users/karl/code/ochazuke/tests/unit/test_webhooks.py", line 36, in event_data
    sig=helpers.get_payload_signature(key, json_event.encode('utf-8')))
  File "/Users/karl/code/ochazuke/ochazuke/webhook/helpers.py", line 28, in get_payload_signature
    key = key.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

----------------------------------------------------------------------
Ran 29 tests in 0.052s

FAILED (errors=8)
```

**Comment by karlcow** [comment]
These are all about the `get_payload_signature` with an attempt to encode a `key` with the value `None` as `utf-8`.

Where does this happen? Line 36 in all tests.
https://github.com/webcompat/webcompat-metrics-server/blob/09a0952434ef507afe37242df6f8b385b8fa49c3/tests/unit/test_webhooks.py#L27-L37

**Comment by karlcow** [comment]
well that's normal. `key` is never assigned a value. 

key is defined as: `key = ochazuke.app.config['HOOK_SECRET_KEY']`

Ah that's normal. This is defined nowhere. :) the `.circleci/config.yml` doesn't matter in the contest of the tests. The setup has even an empty dictionary for the `test_config`

```
        self.app = ochazuke.create_app(test_config={})
```

so basically.
1. needs to create a test config with a key. `SECRETS` is fine
2. make sure that the payload encoded with the SECRET key signature is working.

**Comment by laghee** [comment]
> the .circleci/config.yml doesn't matter in the contest of the tests.

I'm not sure I understand this, @karlcow -- can you explain why? If `.circleci/config.yml` sets a `HOOK_SECRET_KEY` environment variable, why isn't it retrieved and assigned to `key` here?
https://github.com/webcompat/webcompat-metrics-server/blob/09a0952434ef507afe37242df6f8b385b8fa49c3/tests/unit/test_webhooks.py#L24

Or, wait, are you talking about outside CircleCI? Ohhhhh -- you're trying to run these locally, aren't you? And I have mine set up locally with an environment variable... which I forgot to document! 🤦‍♀️  Sorry! OK, gotcha.

**Comment by laghee** [comment]
This is silly, but I'm having a basic issue with syntax.

I can't figure out what Flask wants as the `test_config` argument. I tried `ochazuke.create_app({'HOOK_SECRET_KEY': 'SECRETS'})`
...but that doesn't seem to register, and `test_config` stays `None`.

Then I tried just `{'TESTING': True}`, but `test_config` *still* stays `None`.

Do I need to create a whole config module just for one value? What super-obvious Python/Flask thing am I missing??

**Comment by karlcow** [comment]
In the test file currently, the key is defined out of the context of the app. This `key = ochazuke.app.config['HOOK_SECRET_KEY'] ` is not the app you are dealing with in each test.

The key has probably to be fetch from inside `event_data` or passed as an argument `event_data(filename, hook_key)`.

Then there is the issue of 

```
        self.app = ochazuke.create_app(test_config={'HOOK_SECRET_KEY': 'SECRETS'})
```

We need to understand why this is not working.

Ah! :) 🥁 

https://github.com/webcompat/webcompat-metrics-server/blob/master/ochazuke/__init__.py#L46

**Comment by karlcow** [comment]
We need to wrap this in the `if test_config` statement :)

**Comment by laghee** [comment]
So I had this in `ochazuke/__init__.py`:
<img width="529" alt="screenshot 2018-08-24 03 38 25" src="https://user-images.githubusercontent.com/20972610/44560285-4368d980-a74f-11e8-9ef0-5f140c736ca2.png">

And trying in `test_webhooks` either:

This:
<img width="458" alt="screenshot 2018-08-24 03 39 31" src="https://user-images.githubusercontent.com/20972610/44560449-1bc64100-a750-11e8-8de9-1061e0bc18dc.png">

Or this:

<img width="377" alt="screenshot 2018-08-24 03 41 59" src="https://user-images.githubusercontent.com/20972610/44560395-d0ac2e00-a74f-11e8-8427-6e96682a77ca.png">

I still got 8 errors of this (same as the original issue): 
<img width="516" alt="screenshot 2018-08-24 03 40 30" src="https://user-images.githubusercontent.com/20972610/44560338-8165fd80-a74f-11e8-8f78-aab4b9dde939.png">

...BUT if I just assign `key = 'SECRETS'` in both `test_webhooks` and `webhook.helpers.py` ... it works fine. Would it be totally un-kosher to either do that or document the environment variable setup I had originally? Because I'm stumped -- I don't understand why it doesn't seem to acknowledge a `test_config`.

**Comment by karlcow** [comment]
because you are not passing the config. 

this
```python
        self.app = ochazuke.create_app(test_config={'HOOK_SECRET_KEY': 'SECRETS'})
```

and  this

```python
        self.app = ochazuke.create_app({'HOOK_SECRET_KEY': 'SECRETS'})
```
are two different things. :)

**Comment by karlcow** [comment]
Spoiler: I got a working version of the tests ;)

1. key needs to be a byte string on python 3

```python
def get_payload_signature(key, payload):
    """Compute the payload signature given a key."""
    # HMAC requires its key to be encoded bytes
    mac = hmac.new(b'key', msg=payload, digestmod=hashlib.sha1)
    return mac.hexdigest()
```

2. I explicitlely passed the key

```python
# Some machinery for opening our fixture files for posting tests
def event_data(filename, key):
    """Return a tuple with the content and its signature."""
    current_root = os.path.realpath(os.curdir)
    events_path = 'tests/fixtures/webhooks'
    path = os.path.join(current_root, events_path, filename)
    with open(path, 'r') as f:
        json_event = json.dumps(json.load(f))
    sig = helpers.get_payload_signature(key, json_event.encode('utf-8'))
    signature = 'sha1={sig}'.format(sig=sig)
    return json_event, signature
```

3. I put testing true in the setup and assigned the key

```python
    def setUp(self):
        """Set up tests."""
        self.app = ochazuke.create_app(test_config={'TESTING': True})
        # binds app to the current context
        self.app_context = self.app.app_context()
        self.app_context.push()
        self.key = self.app.config['HOOK_SECRET_KEY']
```

4. for each test, I pass the key.

```python
    def test_fail_on_invalid_event_type(self):
        """POST with event other than 'issues', 'milestone', 'label', or
        'ping' fails."""
        json_event, signature = event_data('issue_body_edited.json', self.key)
```

```
→ nose2 -v tests.unit.test_webhooks.TestWebhooks
test_add_new_event (tests.unit.test_webhooks.TestWebhooks)
A database event object is created correctly and inserted. ... ok
test_add_new_issue (tests.unit.test_webhooks.TestWebhooks)
A database issue object is created correctly and inserted. ... ok
test_extract_issue_event_info (tests.unit.test_webhooks.TestWebhooks)
Extract the right information from an issue event. ... ok
test_fail_on_bogus_signature (tests.unit.test_webhooks.TestWebhooks)
POST with bogus signature on ghevents webhook is forbidden. ... ok
test_fail_on_invalid_event_type (tests.unit.test_webhooks.TestWebhooks)
POST with event other than 'issues', 'milestone', 'label', or ... ok
test_fail_on_missing_signature (tests.unit.test_webhooks.TestWebhooks)
POST without signature on ghevents webhook is forbidden. ... ok
test_forbidden_get (tests.unit.test_webhooks.TestWebhooks)
GET is forbidden on ghevents webhook. ... ok
test_ignore_undesirable_issue_action (tests.unit.test_webhooks.TestWebhooks)
Uninteresting issue actions are accepted but not processed. ... ok
test_ignore_unimportant_milestone_action (tests.unit.test_webhooks.TestWebhooks)
Uninteresting milestone actions are accepted but not processed. ... ok
test_ignore_unknown_action (tests.unit.test_webhooks.TestWebhooks)
POST with an unknown action fails. ... ok
test_is_github_hook (tests.unit.test_webhooks.TestWebhooks)
Validation tests for GitHub Webhooks. ... ok
test_issue_label_change (tests.unit.test_webhooks.TestWebhooks)
Successfully change an issue's label in the issue table. ... ok
test_issue_milestone_change (tests.unit.test_webhooks.TestWebhooks)
Successfully change an issue's milestone in the issue table. ... ok
test_issue_status_change (tests.unit.test_webhooks.TestWebhooks)
Successfully change an issue's status in the issue table. ... ok
test_issue_title_edit (tests.unit.test_webhooks.TestWebhooks)
Successfully update an issue title in the issue table. ... ok
test_process_label_event_info (tests.unit.test_webhooks.TestWebhooks)
Successfully add, edit, and delete labels in the label table. ... ok
test_process_milestone_event_info (tests.unit.test_webhooks.TestWebhooks)
Successfully add, edit, and delete milestones in the table. ... ok
test_success_on_ping_event (tests.unit.test_webhooks.TestWebhooks)
POST with PING events just return a 200 and contains pong. ... ok

----------------------------------------------------------------------
Ran 18 tests in 0.052s

OK
```

**Comment by laghee** [comment]
OK! I have now read up more on keyword arguments and no longer feel like I'm clawing a path in the dark. 😁
It seems to work fine with the key as a global variable, too, but maybe it's neater to have it declared in the testing setup. Looks nicer to me, anyway. I'll send in a PR shortly!
